[project]
name = "ppu-clip"
version = "0.1.0"
description = "ì€ë¿Œë¥¼ ìœ„í•œ ì¹˜ì§€ì§ ë‹¤ì‹œë³´ê¸° ì¼ë¶€ êµ¬ê°„ ê³ í™”ì§ˆ ë‹¤ìš´ë¡œë”"
readme = "README.md"
requires-python = ">=3.10"


authors = [
    { name = "messy-snail" }
]

license = { text = "MIT License" }

dependencies = [
    "ffmpeg-python>=0.2.0",
    "loguru>=0.7.3",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "streamlit>=1.52.1",
]

[tool.commitizen] 
name = "cz_conventional_commits" 
tag_format = "v$major.$minor.$patch$prerelease" 
version_scheme = "pep440" 
version_provider = "poetry" 
update_changelog_on_bump = true 
major_version_zero = true 
change_type_map = { "BREAKING CHANGE" = "â— BREAKING CHANGE", "fix" = "ğŸ› Fixes", "feat" = "âœ¨ Features", "docs" = "ğŸ“– Document", "style" = "ğŸ‘“ Style", "refactor" = "â™»ï¸ Refactor", "perf" = "âš¡ Performance", "test" = "ğŸ’¯ Test", "build" = "ğŸ—ï¸ Build", "ci" = "ğŸ¤– CI" }